services:
  backend:
    build: ./backend
    container_name: grupo4-backend
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: servicou
      DB_NAME: escala_db
      DB_PORT: 3306
      PORT: 3000
    restart: always

  frontend:
    build: ./frontend
    container_name: grupo4-frontend
    ports:
      - "3001:3000"
    environment:
      - WDS_SOCKET_PORT=0
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: always
    depends_on:
      - backend

  mysql:
    image: mysql:8
    container_name: grupo4-mysql
    environment:
      MYSQL_ROOT_PASSWORD: servicou
      MYSQL_DATABASE: escala_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: grupo4-phpmyadmin
    depends_on:
      - mysql
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: servicou
    restart: always

volumes:
  mysql_data: