services:
  backend:
    build: ./backend
    container_name: grupo4-backend
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: escala_db
    restart: always

  frontend:
    image: nginx:alpine
    container_name: grupo4-frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    restart: always

  mysql:
    image: mysql:8
    container_name: grupo4-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: escala_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data: